"""Initial schema

Revision ID: e0a1a751db97
Revises: 
Create Date: 2026-10-04 15:48:52.225001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a1a751db97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_provider_status',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_successful_fetch', sa.DateTime(), nullable=True),
    sa.Column('last_source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('stations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('alert_key', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('acked', sa.Boolean(), nullable=False),
    sa.Column('acked_by', sa.String(length=255), nullable=True),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'alert_key', 'status', name='uq_station_alert_active')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_station_id'), ['station_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('asset_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('capacity_kw', sa.Float(), nullable=True),
    sa.Column('operational_hours', sa.Integer(), nullable=True),
    sa.Column('last_service_date', sa.String(length=20), nullable=True),
    sa.Column('next_service_date', sa.String(length=20), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('facility', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'asset_key', name='uq_station_asset')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('generation_kw', sa.Float(), nullable=False),
    sa.Column('demand_kw', sa.Float(), nullable=False),
    sa.Column('capacity_kw', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('fuel_consumption_l', sa.Float(), nullable=True),
    sa.Column('generator_load_pct', sa.Float(), nullable=True),
    sa.Column('base_load_kw', sa.Float(), nullable=True),
    sa.Column('heating_load_kw', sa.Float(), nullable=True),
    sa.Column('water_load_kw', sa.Float(), nullable=True),
    sa.Column('lab_load_kw', sa.Float(), nullable=True),
    sa.Column('communications_load_kw', sa.Float(), nullable=True),
    sa.Column('lighting_load_kw', sa.Float(), nullable=True),
    sa.Column('other_load_kw', sa.Float(), nullable=True),
    sa.Column('energy_status', sa.String(length=30), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_snapshots_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('environment_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'source_name', 'source_timestamp', name='uq_public_environment_observation')
    )
    with op.batch_alter_table('environment_observations', schema=None) as batch_op:
        batch_op.create_index('ix_environment_observations_station_time', ['station_id', 'timestamp'], unique=False)

    op.create_table('environment_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('snow', sa.Float(), nullable=False),
    sa.Column('visibility', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environment_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_readings_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_readings_timestamp'), ['timestamp'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('item_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('min_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'item_key', name='uq_station_item')
    )
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('parts', sa.String(length=255), nullable=True),
    sa.Column('required_parts', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('maintenance_state', sa.String(length=30), nullable=False),
    sa.Column('readiness', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_station_id'), ['station_id'], unique=False)

    op.create_table('resupply_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('expected_date', sa.String(length=20), nullable=False),
    sa.Column('cargo_description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resupply_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resupply_schedules_station_id'), ['station_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=True),
    sa.Column('vib_warn', sa.Float(), nullable=True),
    sa.Column('vib_crit', sa.Float(), nullable=True),
    sa.Column('battery_warn', sa.Float(), nullable=True),
    sa.Column('temp_warn', sa.Float(), nullable=True),
    sa.Column('wind_warn', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_station_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'station_id')
    )
    op.create_table('asset_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_readings_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_asset_readings_asset_time', ['asset_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_readings_timestamp'), ['timestamp'], unique=False)

    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('previous_quantity', sa.Float(), nullable=True),
    sa.Column('quantity_change', sa.Float(), nullable=False),
    sa.Column('resulting_quantity', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_station_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_item_id'))

    op.drop_table('inventory_transactions')
    with op.batch_alter_table('asset_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_readings_timestamp'))
        batch_op.drop_index('ix_asset_readings_asset_time')
        batch_op.drop_index(batch_op.f('ix_asset_readings_asset_id'))

    op.drop_table('asset_readings')
    op.drop_table('user_station_access')
    op.drop_table('system_settings')
    with op.batch_alter_table('resupply_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resupply_schedules_station_id'))

    op.drop_table('resupply_schedules')
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_station_id'))

    op.drop_table('maintenance_tasks')
    op.drop_table('inventory_items')
    with op.batch_alter_table('environment_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_environment_readings_station_id'))

    op.drop_table('environment_readings')
    with op.batch_alter_table('environment_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_environment_observations_station_time')

    op.drop_table('environment_observations')
    with op.batch_alter_table('energy_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_energy_snapshots_station_id'))

    op.drop_table('energy_snapshots')
    op.drop_table('audit_log')
    op.drop_table('assets')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_station_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    op.drop_table('stations')
    op.drop_table('environment_provider_status')
    # ### end Alembic commands ###
