import {useState} from 'react';import {LineChart,Line,BarChart,Bar as RBar,XAxis,YAxis,Tooltip,CartesianGrid,Legend,ResponsiveContainer,Cell} from 'recharts';
import {useApp} from '../context.jsx';import {useLive} from '../api.js';import {Card,Badge,Loading,Title,COL,tip} from '../components/ui.jsx';
export default function AIAnalytics(){const {station}=useApp();const [d]=useLive(`/api/stations/${station}/predictions`);const [open,setOpen]=useState({});if(!d)return <Loading/>;
  return <><Title sub="Explainable, rule-based detection and forecasting (ML can plug in later)">AI Analytics &amp; Predictive Maintenance</Title>
    <Card title="A · Predictive maintenance">{d.anomalies.length===0&&<p className="mu">No anomalies detected ✨</p>}
      {d.anomalies.map(a=><div key={a.assetId} className={`alert ${a.severity}`}><div className="row" style={{justifyContent:'space-between'}}><b>{a.name} — {a.metric} {a.value}</b><Badge s={a.severity}/></div>
        <small>⏱ {a.urgency}</small><button className="chip" onClick={()=>setOpen({...open,[a.assetId]:!open[a.assetId]})}>{open[a.assetId]?'Hide':'Why this alert?'}</button>
        {open[a.assetId]&&<div><p style={{margin:'8px 0'}}>{a.reason}</p><ResponsiveContainer width="100%" height={90}><LineChart data={a.trend.map((v,i)=>({i,v}))}><YAxis hide domain={['auto','auto']}/><Line dataKey="v" stroke={COL.rose} strokeWidth={2.5} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}</div>)}</Card>
    <Card title="B · Energy forecast (next 24 h)" className="mt" right={<Badge s={d.shortageHours?'critical':'ok'}>{d.shortageHours?`${d.shortageHours} h of shortage`:`peak ${d.peak} kW — within capacity`}</Badge>}>
      <ResponsiveContainer width="100%" height={220}><LineChart data={d.forecast}><CartesianGrid strokeDasharray="3 3" stroke="#e7e1f6"/><XAxis dataKey="h" fontSize={10} interval={2}/><YAxis fontSize={11}/><Tooltip {...tip}/><Legend/>
        <Line dataKey="demand" name="Predicted demand" stroke={COL.peach} strokeWidth={3} dot={false}/><Line dataKey="capacity" name="Available capacity" stroke={COL.sky} strokeDasharray="5 4" dot={false}/><Line dataKey="temp" name="Forecast temp °C" stroke={COL.lav} dot={false}/></LineChart></ResponsiveContainer>
      <p className="mu" style={{fontSize:13}}>Why: colder forecast temperature → higher heating demand → higher total demand. Compared against online generator capacity.</p></Card>
    <Card title="C · Resource forecast (days left vs days to resupply)" className="mt"><ResponsiveContainer width="100%" height={240}><BarChart data={d.resources.map(r=>({...r,daysLeft:Math.min(r.daysLeft,120)}))}><CartesianGrid strokeDasharray="3 3" stroke="#e7e1f6"/><XAxis dataKey="name" fontSize={11}/><YAxis fontSize={11}/><Tooltip {...tip}/><Legend/>
      <RBar dataKey="daysLeft" name="Days left (capped 120)">{d.resources.map((r,i)=><Cell key={i} fill={r.risk==='critical'?COL.rose:r.risk==='warning'?COL.butter:COL.mint}/>)}</RBar><RBar dataKey="resupplyIn" name="Days to resupply" fill={COL.sky}/></BarChart></ResponsiveContainer></Card></>}
