import {Zap,Flame,BatteryCharging,Fuel} from 'lucide-react';import {AreaChart,Area,LineChart,Line,PieChart,Pie,Cell,XAxis,YAxis,Tooltip,CartesianGrid,Legend,ResponsiveContainer} from 'recharts';
import {useApp} from '../context.jsx';import {useLive} from '../api.js';import {Card,Stat,Loading,Title,Chain,COL,PIE,tip} from '../components/ui.jsx';
export default function Energy(){const {station}=useApp();const [en]=useLive(`/api/stations/${station}/energy`);const [pr]=useLive(`/api/stations/${station}/predictions`);
  if(!en||!pr)return <Loading/>;const n=en.now;
  return <><Title sub="Generation, storage, fuel and 24-hour demand forecast">Energy Management</Title>
    <div className="g g4"><Stat icon={Zap} tone="lav" label="Generation" value={`${n.gen} kW`} sub={`capacity ${n.cap} kW`}/><Stat icon={Flame} tone="peach" label="Consumption" value={`${n.demand} kW`} sub={n.deficit>0?`⚠ deficit ${n.deficit} kW`:'covered by generation'}/>
      <Stat icon={BatteryCharging} tone="mint" label="Battery" value={`${n.battery}%`} sub={`${Math.round(n.kwh*n.battery/100)} of ${n.kwh} kWh`}/><Stat icon={Fuel} tone="butter" label="Fuel" value={`${n.fuel.pct}%`} sub={`${n.fuel.daysLeft} days · ${n.fuel.rate} L/day`}/></div>
    <Card title="Cause → effect" className="mt"><Chain items={en.chain}/></Card>
    <div className="g g21 mt"><Card title="Generation vs consumption (kW)"><ResponsiveContainer width="100%" height={250}><AreaChart data={en.history}><CartesianGrid strokeDasharray="3 3" stroke="#e7e1f6"/><XAxis dataKey="t" fontSize={10} minTickGap={40}/><YAxis fontSize={11}/><Tooltip {...tip}/><Legend/>
      <Area dataKey="gen" name="Generation" stroke={COL.lav} fill={COL.lav} fillOpacity={.35} isAnimationActive={false}/><Area dataKey="demand" name="Consumption" stroke={COL.peach} fill={COL.peach} fillOpacity={.3} isAnimationActive={false}/></AreaChart></ResponsiveContainer></Card>
      <Card title="Consumption by system"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={en.breakdown} dataKey="value" nameKey="name" innerRadius={50} outerRadius={85} paddingAngle={3}>{en.breakdown.map((_,i)=><Cell key={i} fill={PIE[i%5]}/>)}</Pie><Tooltip {...tip}/><Legend/></PieChart></ResponsiveContainer></Card></div>
    <div className="g g2 mt"><Card title="Battery charge (%)"><ResponsiveContainer width="100%" height={200}><LineChart data={en.history}><CartesianGrid strokeDasharray="3 3" stroke="#e7e1f6"/><XAxis dataKey="t" hide/><YAxis domain={[0,100]} fontSize={11}/><Tooltip {...tip}/><Line dataKey="battery" stroke={COL.mint} strokeWidth={3} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></Card>
      <Card title="24-hour demand forecast (kW)" right={<span className={`badge ${pr.shortageHours?'crit':'ok'}`}>{pr.shortageHours?`${pr.shortageHours} h shortage`:'no shortage predicted'}</span>}><ResponsiveContainer width="100%" height={200}><LineChart data={pr.forecast}><CartesianGrid strokeDasharray="3 3" stroke="#e7e1f6"/><XAxis dataKey="h" fontSize={10} interval={3}/><YAxis fontSize={11}/><Tooltip {...tip}/><Legend/>
        <Line dataKey="demand" name="Forecast demand" stroke={COL.peach} strokeWidth={3} dot={false}/><Line dataKey="capacity" name="Capacity" stroke={COL.sky} strokeDasharray="5 4" dot={false}/></LineChart></ResponsiveContainer>
        <p className="mu" style={{fontSize:12}}>Forecast = base load + heating demand from forecast temperature (rule-based, simulated).</p></Card></div></>}
